version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/laravel_sample
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_sample_db
      MYSQL_USER: laravel_db_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql

